use_frameworks!

platform :ios, '8.0'

target 'KKWechatPayHelper_Example' do
  pod 'KKWechatPayHelper', :path => '../'

  target 'KKWechatPayHelper_Tests' do
    inherit! :search_paths

    
  end
end
